name: Spring-boot-application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Corrected: Set up JDK 8 with distribution
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Specify the Java distribution

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions
