name: Spring Boot Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' 
          distribution: 'temurin'

      # Install Docker and Docker Compose
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build Docker image
      - name: Build Docker image
        run: docker-compose build

      # Run Docker Compose to start services
      - name: Run Docker Compose
        run: docker-compose up -d

      # Wait for MySQL to start (extended time)
      - name: Wait for MySQL to start (extended)
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..75}; do
            if docker exec mysqldb mysqladmin ping -h localhost --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 5
          done

      # Run Maven tests in the Docker container
      - name: Run Maven tests
        run: docker exec -it springboot-docker-compose-master-springboot-app-1 mvn test -DskipDockerTests=false -X
