on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests -T 1C

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for MySQL to start (extended)
        run: |
          echo "Waiting for MySQL to start..."
          until docker exec mysqldb mysqladmin ping -h localhost --silent; do
            echo "Still waiting for MySQL..."
            sleep 5
          done

      - name: Check Docker Compose logs
        run: docker-compose logs

      - name: Run Maven tests
        run: mvn test -DskipDockerTests=false -X

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports/
