name: Spring Boot Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: saish1717
          password: saish@5000

      - name: Use custom Docker Action
        uses: docker://saish1717/jq:action
