name: Spring-boot-application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'

     
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: mvn clean package -T 1C


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build Docker image
        run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t my-app:latest .


      - name: Run Docker Compose
        run: docker-compose up -d


      - name: Show Docker Compose logs
        run: docker-compose logs


      - name: Wait for services to start
        run: sleep 30


      - name: Run Maven tests
        run: mvn test
