name: Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Change this to your required version
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven using parallel threads and skip tests
      - name: Build with Maven
        run: mvn clean package -DskipTests -T 1C

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image with cache
      - name: Build Docker image
        run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t my-app:latest .

      # Run Docker Compose to start services
      - name: Run Docker Compose
        run: docker-compose up -d

      # Wait for MySQL to be ready
      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if docker exec mysql mysqladmin ping -h localhost --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 5
          done

      # Run Maven tests
      - name: Run Maven tests
        run: mvn test -DskipDockerTests=false
